"""Pytest-Fixtures fuer den Value-Analyzer."""

from __future__ import annotations

import pandas as pd
import pytest


@pytest.fixture
def mock_universe_df() -> pd.DataFrame:
    """Repraesentatives 8-Werte-Universum mit allen Profilen."""
    rows = [
        # Klassisch Value + Quality
        dict(
            symbol="VAL.DE",
            name="Value Co",
            index="DAX",
            sector="Industrials",
            market_cap=5e9,
            price=42,
            currency="EUR",
            ev_ebit=8.0,
            pe_ratio=10,
            pb_ratio=1.2,
            p_fcf=9,
            dividend_yield=0.04,
            buyback_yield=0.02,
            shareholder_yield=0.06,
            roic=0.18,
            roa=0.09,
            fcf_margin=0.15,
            gross_margin=0.35,
            operating_margin=0.18,
            net_debt_ebitda=1.2,
            debt_to_equity=0.5,
            earnings_stability=0.85,
            revenue_growth_5y=0.05,
            eps_growth_5y=0.08,
            errors="",
        ),
        # Teurer Quality-Wert
        dict(
            symbol="QUAL.DE",
            name="Quality Co",
            index="DAX",
            sector="Tech",
            market_cap=20e9,
            price=120,
            currency="EUR",
            ev_ebit=35.0,
            pe_ratio=42,
            pb_ratio=8,
            p_fcf=40,
            dividend_yield=0.01,
            buyback_yield=0,
            shareholder_yield=0.01,
            roic=0.32,
            roa=0.18,
            fcf_margin=0.28,
            gross_margin=0.65,
            operating_margin=0.30,
            net_debt_ebitda=-0.5,
            debt_to_equity=0.2,
            earnings_stability=0.95,
            revenue_growth_5y=0.18,
            eps_growth_5y=0.22,
            errors="",
        ),
        # Value-Trap
        dict(
            symbol="TRAP.DE",
            name="Trap Co",
            index="MDAX",
            sector="Auto",
            market_cap=1e9,
            price=8,
            currency="EUR",
            ev_ebit=5.0,
            pe_ratio=6,
            pb_ratio=0.4,
            p_fcf=4,
            dividend_yield=0.08,
            buyback_yield=0,
            shareholder_yield=0.08,
            roic=0.02,
            roa=0.01,
            fcf_margin=0.02,
            gross_margin=0.12,
            operating_margin=0.03,
            net_debt_ebitda=5.5,
            debt_to_equity=2.5,
            earnings_stability=0.15,
            revenue_growth_5y=-0.02,
            eps_growth_5y=-0.10,
            errors="",
        ),
        # Mittelmaessig
        dict(
            symbol="MID.DE",
            name="Mid Co",
            index="MDAX",
            sector="Consumer",
            market_cap=2e9,
            price=55,
            currency="EUR",
            ev_ebit=14.0,
            pe_ratio=16,
            pb_ratio=2.0,
            p_fcf=15,
            dividend_yield=0.025,
            buyback_yield=0.01,
            shareholder_yield=0.035,
            roic=0.12,
            roa=0.06,
            fcf_margin=0.08,
            gross_margin=0.30,
            operating_margin=0.11,
            net_debt_ebitda=2.0,
            debt_to_equity=0.8,
            earnings_stability=0.6,
            revenue_growth_5y=0.04,
            eps_growth_5y=0.05,
            errors="",
        ),
        # Verlust-Macher (negative EV/EBIT, soll aus Value-Ranking ausgeschlossen werden)
        dict(
            symbol="LOSS.DE",
            name="Loss Co",
            index="MDAX",
            sector="Bio",
            market_cap=800e6,
            price=10,
            currency="EUR",
            ev_ebit=-15.0,
            pe_ratio=None,
            pb_ratio=3,
            p_fcf=None,
            dividend_yield=0,
            buyback_yield=0,
            shareholder_yield=0,
            roic=-0.05,
            roa=-0.03,
            fcf_margin=-0.10,
            gross_margin=0.20,
            operating_margin=-0.08,
            net_debt_ebitda=None,
            debt_to_equity=0.5,
            earnings_stability=0.1,
            revenue_growth_5y=None,
            eps_growth_5y=None,
            errors="",
        ),
        # Zu klein - soll gefiltert werden
        dict(
            symbol="SMALL.DE",
            name="Small Co",
            index="MDAX",
            sector="Tech",
            market_cap=100e6,
            price=5,
            currency="EUR",
            ev_ebit=10.0,
            pe_ratio=12,
            pb_ratio=1,
            p_fcf=8,
            dividend_yield=0.03,
            buyback_yield=0,
            shareholder_yield=0.03,
            roic=0.15,
            roa=0.08,
            fcf_margin=0.12,
            gross_margin=0.4,
            operating_margin=0.14,
            net_debt_ebitda=1,
            debt_to_equity=0.4,
            earnings_stability=0.7,
            revenue_growth_5y=0.05,
            eps_growth_5y=0.06,
            errors="",
        ),
        # Solider Dividendenwert
        dict(
            symbol="OK.DE",
            name="OK Co",
            index="DAX",
            sector="Utility",
            market_cap=10e9,
            price=33,
            currency="EUR",
            ev_ebit=11.0,
            pe_ratio=14,
            pb_ratio=1.5,
            p_fcf=12,
            dividend_yield=0.05,
            buyback_yield=0.005,
            shareholder_yield=0.055,
            roic=0.10,
            roa=0.05,
            fcf_margin=0.10,
            gross_margin=0.25,
            operating_margin=0.13,
            net_debt_ebitda=2.5,
            debt_to_equity=1.0,
            earnings_stability=0.7,
            revenue_growth_5y=0.03,
            eps_growth_5y=0.04,
            errors="",
        ),
        # Hoechste Verschuldung
        dict(
            symbol="LEV.DE",
            name="Leverage Co",
            index="MDAX",
            sector="RealEst",
            market_cap=3e9,
            price=18,
            currency="EUR",
            ev_ebit=22.0,
            pe_ratio=25,
            pb_ratio=0.7,
            p_fcf=30,
            dividend_yield=0.06,
            buyback_yield=0,
            shareholder_yield=0.06,
            roic=0.04,
            roa=0.02,
            fcf_margin=0.05,
            gross_margin=0.20,
            operating_margin=0.06,
            net_debt_ebitda=8.0,
            debt_to_equity=3.5,
            earnings_stability=0.5,
            revenue_growth_5y=0.02,
            eps_growth_5y=-0.01,
            errors="",
        ),
    ]
    return pd.DataFrame(rows)
