"""Initiales Schema: batch, market_data, scoring, reporting inkl. Loeschschutz

Revision ID: 0001
Revises:
Erstellt: 2026-09-30

Nur additiv: keine Tabelle/Spalte mit Daten entfernen. Neue Tabellen mit
``protect_table()`` aus ``src.db.ddl`` schuetzen.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db.ddl import CREATE_FUNCTIONS, SCHEMAS, grant_statements, protect_table

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = (
    "batch.run",
    "batch.run_log",
    "batch.import_file",
    "market_data.instrument",
    "market_data.fetch_run",
    "market_data.universe_member",
    "market_data.raw_info",
    "market_data.statement_value",
    "market_data.fx_rate",
    "market_data.fundamental_snapshot",
    "scoring.scoring_run",
    "scoring.score_result",
    "scoring.factor_score",
    "reporting.report",
    "reporting.delivery",
)


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ### commands auto generated by Alembic ###
    op.create_table(
        "run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("app_version", sa.Text(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("force_refresh", sa.Boolean(), nullable=False),
        sa.Column("universe_mode", sa.Text(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=True),
        sa.Column("scoring_run_id", sa.BigInteger(), nullable=True),
        sa.Column("report_id", sa.BigInteger(), nullable=True),
        sa.Column("universe_size", sa.BigInteger(), nullable=True),
        sa.Column("scored_count", sa.BigInteger(), nullable=True),
        sa.Column("failed_count", sa.BigInteger(), nullable=True),
        sa.Column("exit_code", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("kind IN ('batch', 'rescore', 'import')", name=op.f("ck_run_kind")),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'partial', 'no_data', 'failed')",
            name=op.f("ck_run_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
        schema="batch",
    )
    op.create_table(
        "fetch_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_version", sa.Text(), nullable=True),
        sa.Column("universe_source", sa.Text(), nullable=True),
        sa.Column("universe_as_of", sa.Date(), nullable=True),
        sa.Column("universe_size", sa.BigInteger(), nullable=True),
        sa.Column("ok_count", sa.BigInteger(), nullable=True),
        sa.Column("success_share", sa.Double(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint("origin IN ('live', 'import')", name=op.f("ck_fetch_run_origin")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetch_run")),
        schema="market_data",
    )
    op.create_table(
        "instrument",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("isin", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
        sa.UniqueConstraint("isin", name=op.f("uq_instrument_isin")),
        sa.UniqueConstraint("symbol", name=op.f("uq_instrument_symbol")),
        schema="market_data",
    )
    op.create_table(
        "report",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("scoring_run_id", sa.BigInteger(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("csv_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("csv_filename", sa.Text(), nullable=False),
        sa.Column("top_n", sa.BigInteger(), nullable=False),
        sa.Column("bottom_n", sa.BigInteger(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report")),
        schema="reporting",
    )
    op.create_index(
        op.f("ix_report_run_id"), "report", ["run_id"], unique=False, schema="reporting"
    )
    op.create_table(
        "scoring_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config_hash", sa.Text(), nullable=True),
        sa.Column("app_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "origin IN ('live', 'rescore', 'import')", name=op.f("ck_scoring_run_origin")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_run")),
        schema="scoring",
    )
    op.create_index(
        op.f("ix_scoring_run_config_hash"),
        "scoring_run",
        ["config_hash"],
        unique=False,
        schema="scoring",
    )
    op.create_table(
        "import_file",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["batch.run.id"], name=op.f("fk_import_file_run_id_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_file")),
        sa.UniqueConstraint("sha256", name=op.f("uq_import_file_sha256")),
        schema="batch",
    )
    op.create_table(
        "run_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("logger", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["batch.run.id"], name=op.f("fk_run_log_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_log")),
        schema="batch",
    )
    op.create_index(op.f("ix_run_log_run_id"), "run_log", ["run_id"], unique=False, schema="batch")
    op.create_table(
        "fundamental_snapshot",
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("index_name", sa.Text(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("financial_currency", sa.Text(), nullable=True),
        sa.Column("price", sa.Double(), nullable=True),
        sa.Column("market_cap", sa.Double(), nullable=True),
        sa.Column("enterprise_value", sa.Double(), nullable=True),
        sa.Column("shares_outstanding", sa.Double(), nullable=True),
        sa.Column("ev_ebit", sa.Double(), nullable=True),
        sa.Column("pe_ratio", sa.Double(), nullable=True),
        sa.Column("pb_ratio", sa.Double(), nullable=True),
        sa.Column("p_fcf", sa.Double(), nullable=True),
        sa.Column("dividend_yield", sa.Double(), nullable=True),
        sa.Column("buyback_yield", sa.Double(), nullable=True),
        sa.Column("shareholder_yield", sa.Double(), nullable=True),
        sa.Column("roic", sa.Double(), nullable=True),
        sa.Column("roa", sa.Double(), nullable=True),
        sa.Column("fcf_margin", sa.Double(), nullable=True),
        sa.Column("gross_margin", sa.Double(), nullable=True),
        sa.Column("operating_margin", sa.Double(), nullable=True),
        sa.Column("net_debt_ebitda", sa.Double(), nullable=True),
        sa.Column("debt_to_equity", sa.Double(), nullable=True),
        sa.Column("earnings_stability", sa.Double(), nullable=True),
        sa.Column("revenue_growth_5y", sa.Double(), nullable=True),
        sa.Column("eps_growth_5y", sa.Double(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fiscal_period_end", sa.Date(), nullable=True),
        sa.Column("statement_fx", sa.Double(), nullable=True),
        sa.Column("fetch_ok", sa.Boolean(), nullable=False),
        sa.Column("errors", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["market_data.fetch_run.id"],
            name=op.f("fk_fundamental_snapshot_fetch_run_id_fetch_run"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["market_data.instrument.id"],
            name=op.f("fk_fundamental_snapshot_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint(
            "fetch_run_id", "instrument_id", name=op.f("pk_fundamental_snapshot")
        ),
        schema="market_data",
    )
    op.create_table(
        "fx_rate",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=False),
        sa.Column("from_ccy", sa.Text(), nullable=False),
        sa.Column("to_ccy", sa.Text(), nullable=False),
        sa.Column("rate", sa.Double(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["market_data.fetch_run.id"],
            name=op.f("fk_fx_rate_fetch_run_id_fetch_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rate")),
        sa.UniqueConstraint(
            "fetch_run_id",
            "from_ccy",
            "to_ccy",
            name=op.f("uq_fx_rate_fetch_run_id_from_ccy_to_ccy"),
        ),
        schema="market_data",
    )
    op.create_table(
        "raw_info",
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["market_data.fetch_run.id"],
            name=op.f("fk_raw_info_fetch_run_id_fetch_run"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["market_data.instrument.id"],
            name=op.f("fk_raw_info_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("fetch_run_id", "instrument_id", name=op.f("pk_raw_info")),
        schema="market_data",
    )
    op.create_table(
        "statement_value",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Text(), nullable=False),
        sa.Column("line_item", sa.Text(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("first_seen_fetch_run_id", sa.BigInteger(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "statement IN ('income', 'balance', 'cashflow')",
            name=op.f("ck_statement_value_statement"),
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_fetch_run_id"],
            ["market_data.fetch_run.id"],
            name=op.f("fk_statement_value_first_seen_fetch_run_id_fetch_run"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["market_data.instrument.id"],
            name=op.f("fk_statement_value_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statement_value")),
        schema="market_data",
    )
    op.create_index(
        "ix_statement_value_key",
        "statement_value",
        ["instrument_id", "statement", "frequency", "line_item", "period_end", "first_seen_at"],
        unique=False,
        schema="market_data",
    )
    op.create_table(
        "universe_member",
        sa.Column("fetch_run_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("index_name", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["market_data.fetch_run.id"],
            name=op.f("fk_universe_member_fetch_run_id_fetch_run"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["market_data.instrument.id"],
            name=op.f("fk_universe_member_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("fetch_run_id", "instrument_id", name=op.f("pk_universe_member")),
        schema="market_data",
    )
    op.create_table(
        "delivery",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("report_id", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("recipient", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("channel IN ('mail', 'healthcheck')", name=op.f("ck_delivery_channel")),
        sa.CheckConstraint(
            "kind IN ('report', 'error', 'ping_ok', 'ping_fail')", name=op.f("ck_delivery_kind")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reporting.report.id"], name=op.f("fk_delivery_report_id_report")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery")),
        schema="reporting",
    )
    op.create_index(
        op.f("ix_delivery_run_id"), "delivery", ["run_id"], unique=False, schema="reporting"
    )
    op.create_table(
        "factor_score",
        sa.Column("scoring_run_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("factor_key", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("source_column", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Double(), nullable=True),
        sa.Column("percentile_rank", sa.Double(), nullable=True),
        sa.CheckConstraint(
            "category IN ('value', 'quality')", name=op.f("ck_factor_score_category")
        ),
        sa.CheckConstraint("direction IN ('low', 'high')", name=op.f("ck_factor_score_direction")),
        sa.ForeignKeyConstraint(
            ["scoring_run_id"],
            ["scoring.scoring_run.id"],
            name=op.f("fk_factor_score_scoring_run_id_scoring_run"),
        ),
        sa.PrimaryKeyConstraint(
            "scoring_run_id", "instrument_id", "factor_key", name=op.f("pk_factor_score")
        ),
        schema="scoring",
    )
    op.create_table(
        "score_result",
        sa.Column("scoring_run_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("passed_filter", sa.Boolean(), nullable=False),
        sa.Column("value_score", sa.Double(), nullable=True),
        sa.Column("quality_score", sa.Double(), nullable=True),
        sa.Column("composite_score", sa.Double(), nullable=True),
        sa.Column("value_trap_flag", sa.Boolean(), nullable=True),
        sa.Column("rank_overall", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scoring_run_id"],
            ["scoring.scoring_run.id"],
            name=op.f("fk_score_result_scoring_run_id_scoring_run"),
        ),
        sa.PrimaryKeyConstraint("scoring_run_id", "instrument_id", name=op.f("pk_score_result")),
        schema="scoring",
    )
    # ### end Alembic commands ###

    # Niemals loeschen/ueberschreiben - erzwungen in der Datenbank selbst
    op.execute(CREATE_FUNCTIONS)
    for table in TABLES:
        for statement in protect_table(table):
            op.execute(statement)
    op.execute(grant_statements())


def downgrade() -> None:
    msg = "Downgrades wuerden Daten loeschen und sind nicht vorgesehen"
    raise NotImplementedError(msg)
